In [44]:
import pandas as pd
import numpy as np
import scipy.linalg
from scipy.linalg import cho_factor, cho_solve

In [45]:
# reading in the dataset
data = pd.read_csv("https://raw.githubusercontent.com/anchalamba/STA141C/main/data/SpotifyData_LR.csv")
df = pd.DataFrame(data)
df.head()
pd.set_option('display.max_columns', None)

In [46]:
df.insert(0, "intercept", 1, True)

In [47]:
df

intercept    bpm  nrgy  dnce   dB  live   val    dur  acous  spch  \
0            1  140.0  81.0  61.0 -6.0  23.0  23.0  203.0    0.0   6.0   
1            1  138.0  89.0  68.0 -4.0  36.0  83.0  192.0    1.0   8.0   
2            1   95.0  48.0  84.0 -7.0   9.0  96.0  243.0   20.0   3.0   
3            1   93.0  87.0  66.0 -4.0   4.0  38.0  180.0   11.0  12.0   
4            1  104.0  85.0  69.0 -6.0   9.0  74.0  268.0   39.0   5.0   
..         ...    ...   ...   ...  ...   ...   ...    ...    ...   ...   
995          1  155.0  73.0  83.0 -4.0  12.0  45.0  313.0    1.0  22.0   
996          1   80.0  50.0  55.0 -9.0  80.0  41.0  190.0   23.0   7.0   
997          1  103.0  77.0  89.0 -5.0   9.0  46.0  177.0    1.0   7.0   
998          1  138.0  58.0  53.0 -6.0  10.0  59.0  214.0    1.0  10.0   
999          1   98.0  59.0  80.0 -7.0  13.0  18.0  200.0    2.0  15.0   

     2010.0  2011.0  2012.0  2013.0  2014.0  2015.0  2016.0  2017.0  2018.0  \
0         1       0       0       0       0       0       0       0       0   
1         1       0       0       0       0       0       0       0       0   
2         1       0       0       0       0       0       0       0       0   
3         1       0       0       0       0       0       0       0       0   
4         1       0       0       0       0       0       0       0       0   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
995       0       0       0       0       0       0       0       0       0   
996       0       0       0       0       0       0       0       0       0   
997       0       0       0       0       0       0       0       0       0   
998       0       0       0       0       0       0       0       0       0   
999       0       0       0       0       0       0       0       0       0   

     2019.0  boy band  country  dance  dance pop  edm  hip hop  house  indie  \
0         0         0        0      0          1    0        0      0      0   
1         0         0        0      0          1    0        0      0      0   
2         0         0        0      0          0    0        0      0      0   
3         0         0        0      0          0    0        1      0      0   
4         0         0        0      0          0    0        1      0      0   
..      ...       ...      ...    ...        ...  ...      ...    ...    ...   
995       1         0        0      0          0    0        1      0      0   
996       1         0        0      0          0    0        1      0      0   
997       1         0        0      0          0    0        0      0      0   
998       1         0        0      0          0    0        0      0      0   
999       1         0        0      0          0    0        1      0      0   

     other  pop  r&b  rap  rock  Band/Group  Duo  Solo  Trio  pop_transformed2  
0        0    0    0    0     0           0    1     0     0         -0.688503  
1        0    0    0    0     0           0    1     0     0         -0.893216  
2        0    1    0    0     0           0    0     1     0         -0.470267  
3        0    0    0    0     0           0    0     1     0          0.547680  
4        0    0    0    0     0           0    0     1     0          0.407101  
..     ...  ...  ...  ...   ...         ...  ...   ...   ...               ...  
995      0    0    0    0     0           0    0     1     0          1.477293  
996      0    0    0    0     0           0    0     1     0          1.311786  
997      1    0    0    0     0           0    0     1     0         -0.893216  
998      1    0    0    0     0           0    1     0     0         -0.990653  
999      0    0    0    0     0           0    0     1     0         -0.116493  

[1000 rows x 38 columns]

In [48]:
x = df.loc[:, ~df.columns.isin(['pop_transformed2', '2010.0', '2011.0', '2012.0', '2013.0', '2014.0', '2015.0', '2016.0', '2017.0', '2018.0', '2019.0'])]
y = df.iloc[:, -1]

In [34]:
L, Lt = cho_factor(xtx, lower = True)

#B_chol = cho_solve((L, Lt), Xty)
#B_chol

In [52]:
np.linalg.eigvals(xtx)

array([ 7.69491390e+07,  1.08949932e+06,  5.82451189e+05,  4.17869112e+05,
        2.11862816e+05,  1.87184813e+05,  1.42187729e+05,  7.63613114e+04,
        2.83456654e+03,  3.14039464e+02,  2.39128636e+02,  1.49888654e+02,
        1.04373176e+02,  9.47179782e+01,  6.98673188e+01,  3.40647861e+01,
        2.60417200e+01,  5.28244147e+00,  1.82023164e+01,  9.81918485e+00,
        1.17833063e+01,  1.67221442e+01,  1.39113166e+01,  1.54896772e+01,
        1.48368651e+01,  7.79073889e-12, -1.53729807e-14])

In [53]:
#cholesky factorization of A (xtx)
c_and_lower = scipy.linalg.cho_factor(xtx, lower = True)
c_and_lower

(array([[ 3.16227766e+01,  1.21262000e+05,  6.95020000e+04,
          6.68760000e+04, -5.66300000e+03,  1.79110000e+04,
          5.09010000e+04,  2.20406000e+05,  1.43690000e+04,
          1.00640000e+04,  2.10000000e+01,  1.40000000e+01,
          1.50000000e+01,  3.61000000e+02,  1.70000000e+01,
          1.26000000e+02,  1.10000000e+01,  1.10000000e+01,
          1.08000000e+02,  1.99000000e+02,  1.60000000e+01,
          6.20000000e+01,  3.90000000e+01,  1.69000000e+02,
          7.00000000e+01,  7.48000000e+02,  1.30000000e+01],
        [ 3.83464114e+03,  8.29304140e+02,  8.47755300e+06,
          8.07111200e+06, -6.81952000e+05,  2.17708900e+06,
          6.18429900e+06,  2.67095660e+07,  1.67887000e+06,
          1.25670100e+06,  2.60800000e+03,  1.93200000e+03,
          1.82100000e+03,  4.33430000e+04,  2.00500000e+03,
          1.53700000e+04,  1.37100000e+03,  1.40800000e+03,
          1.31170000e+04,  2.35170000e+04,  2.04300000e+03,
          8.02200000e+03,  4.70500000e+

In [54]:
#solving the linear equations of Ax = b, b is xty and A is the cholesky factorization we got above
beta_hat_ch = scipy.linalg.cho_solve(c_and_lower, x.transpose() @ y)
beta_hat_ch

array([-3.68552967e+00,  2.99206664e-04, -1.36428838e-02,  2.12608218e-03,
        2.91988912e-02, -6.33357903e-03,  3.53884121e-03,  5.53547764e-04,
        2.89304180e-03, -5.08236352e-04,  1.69890582e+00,  1.02854384e+00,
        6.11437418e-01,  1.47342451e+00,  1.20474057e+00,  1.73975710e+00,
        1.83466088e-01,  1.46942779e+00,  1.32840377e+00,  1.58378794e+00,
        1.90066108e+00,  1.91899645e+00,  1.83071108e+00,  2.97390930e+00,
        2.77319113e+00,  2.85970567e+00,  2.40357546e+00])

In [55]:
#calculating cholesky value
L = np.linalg.cholesky(xtx)
L

array([[ 3.16227766e+01,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 3.83464114e+03,  8.29304140e+02,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+

In [56]:
#using the property L^t beta = l
sm_l = L.transpose() @ beta_hat_ch
sm_l

array([-3.89901176e-14, -6.95187533e-01, -7.34893024e+00,  1.60366288e+00,
        8.72789673e-01, -2.44015953e+00,  2.26849813e+00,  3.58847867e-01,
        1.08434196e+00,  8.26780931e-01,  1.26823010e+00, -1.81889816e+00,
       -3.59722452e+00, -1.70527706e+00, -1.78099805e+00,  1.16899896e+00,
       -4.70903477e+00, -8.17244888e-02, -3.32347547e+00, -2.69747546e+00,
       -7.05907834e-02,  8.91104562e-02,  9.27159322e-07,  1.25139991e+00,
       -5.99524199e-01,  1.59767133e+00,  3.96240096e-07])

## Variance and Standard Error of $\hat\beta$

In [57]:
#variance
var_ch = (y.transpose() @ y - sm_l.transpose() @ sm_l)/(x.shape[0] - x.shape[1])
var_ch

0.8826208430242212

In [58]:
#standard error
se_ch = np.sqrt(var_ch * np.diag(scipy.linalg.inv(L @ L.transpose())))
se_ch

C:\Users\ykw22\AppData\Local\Temp\ipykernel_28376\2617535180.py:2: RuntimeWarning: invalid value encountered in sqrt
  se_ch = np.sqrt(var_ch * np.diag(scipy.linalg.inv(L @ L.transpose())))


array([4.37733944e+06, 1.18446837e-03, 3.07817884e-03, 2.71447108e-03,
       2.17705681e-02, 2.29133141e-03, 1.64521894e-03, 7.79228208e-04,
       1.86311524e-03, 3.60821687e-03, 3.32796023e+06, 3.40552651e+06,
       3.31468199e+06, 3.41952202e+06, 3.56072761e+06, 3.31799171e+06,
       3.46861735e+06, 3.46861735e+06, 3.60384335e+06, 3.45270205e+06,
       3.28495227e+06, 3.44558872e+06, 3.36622883e+06,            nan,
                  nan,            nan,            nan])